Reading mnemonic

diff --git a/logger-server b/logger-server
--- a/logger-server
+++ b/logger-server
@@ -4,9 +4,11 @@ SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 LOGGER_DIR=${LOGGER_PATH:-${SCRIPTPATH}/server}
 export PYTHONPATH=${LOGGER_DIR}/proto:${LOGGER_DIR}/../logger
 
-if [[ -z "${CARTESI_CONCERN_KEY}" ]] || [[ -z "${CARTESI_CONCERN_ADDRESS}" ]]; then
-    echo "Error: CARTESI_CONCERN_KEY and CARTESI_CONCERN_ADDRESS must be defined!"
-    exit 1;
+if [[ -z "${MNEMONIC}" ]]; then
+    if [[ -z "${CARTESI_CONCERN_KEY}" ]] || [[ -z "${CARTESI_CONCERN_ADDRESS}" ]]; then
+        echo "Error: either MNEMONIC or both CARTESI_CONCERN_KEY and CARTESI_CONCERN_ADDRESS must be defined!"
+        exit 1;
+    fi
 fi
 
 cd ${LOGGER_DIR} && python3 logger_server.py $@
